version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/app
      - ./logs:/app/logs
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - FLASK_APP=app.py
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/game_db
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
    command: flask run --host=0.0.0.0 --port=5000

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/conf.d/dev.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static
      - ./logs/nginx:/var/log/nginx
    ports:
      - "80:80"
    depends_on:
      - app

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=game_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  redis_data: 